(define (make-monitered func)
  (define theFunction func)
  (define localStateCnt 0)
  (define (reset) (set! localStateCnt 0))
  (define (increment) (set! localStateCnt (+ localStateCnt 1)))
  (define (dispatch message)
    (cond ((eq? message 'how-many-calls?) localStateCnt)
          ((eq? message 'reset-count) (reset))
          (else  (increment)(theFunction message) )
          ))dispatch)
(define a (make-monitered square))
;(a 4)
;(a 3)
;(a 4)
;(a 'how-many-calls?)
;(a 'reset-count)
;(a 'how-many-calls?)

