(son Adam Cain)
(son Cain Enoch)
(son Enoch Irad)
(son Irad Mehujael)
(son Mehujael Methushael)
(son Methushael Lamech)
(wife Lamech Ada)
(son Ada Jabal)
(son Ada Jubal)
(rule (grandson-is ?s ?f ?g)
    (and (son ?f ?s) 
        (son ?g ?f)))

(rule (son-of-man's-wife ?w ?m ?s)
    (and (wife ?w ?m)
        (son ?m ?s)))